apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: AUTH_IMAGE_PLACEHOLDER
    newName: ghcr.io/hyunshu12/helpbee/auth-service
    newTag: stable
  - name: USER_IMAGE_PLACEHOLDER
    newName: ghcr.io/hyunshu12/helpbee/user-service
    newTag: stable
  - name: ANALYSIS_IMAGE_PLACEHOLDER
    newName: ghcr.io/hyunshu12/helpbee/analysis-service
    newTag: stable
